import { shopifyGraphql } from "./graphql";
import type { ShopifyVariant } from "@/types/shopify";
import type { KiotVietProduct } from "@/lib/kiotviet/types";

export function getShopifyVariants(after?:string){return shopifyGraphql<{productVariants:{nodes:ShopifyVariant[];pageInfo:{hasNextPage:boolean;endCursor?:string}}}>(`query Variants($after:String){productVariants(first:100,after:$after){nodes{id sku barcode product{id title} inventoryItem{id tracked}} pageInfo{hasNextPage endCursor}}}`,{after:after??null});}
export async function findShopifyVariantsBySku(sku:string){const data=await shopifyGraphql<{productVariants:{nodes:ShopifyVariant[]}}>(`query BySku($query:String!){productVariants(first:10,query:$query){nodes{id sku barcode product{id title} inventoryItem{id tracked}}}}`,{query:`sku:${sku}`});return data.productVariants.nodes;}

type ManagedVariant = ShopifyVariant & { price?: string };
function productInput(product:KiotVietProduct){return{title:product.name,descriptionHtml:product.description??"",productType:product.categoryName??"",vendor:"KiotViet",status:product.isActive===false||product.allowsSale===false?"DRAFT":"ACTIVE"};}
function productMedia(product:KiotVietProduct){return (product.images??[]).filter((url)=>{try{return new URL(url).protocol==="https:";}catch{return false;}}).slice(0,20).map((originalSource)=>({originalSource,alt:product.name,mediaContentType:"IMAGE" as const}));}
async function productHasMedia(productId:string){const data=await shopifyGraphql<{product:{media:{nodes:Array<{id:string}>}}|null}>(`query ProductMedia($id:ID!){product(id:$id){media(first:1){nodes{id}}}}`,{id:productId});return Boolean(data.product?.media.nodes.length);}

export async function createShopifyProduct(product:KiotVietProduct):Promise<ManagedVariant>{const created=await shopifyGraphql<{productCreate:{product?:{id:string;variants:{nodes:Array<{id:string}>}};userErrors:Array<{message:string}>}}>(`mutation CreateProduct($product:ProductCreateInput!,$media:[CreateMediaInput!]){productCreate(product:$product,media:$media){product{id variants(first:1){nodes{id}}} userErrors{message}}}`,{product:productInput(product),media:productMedia(product)});if(created.productCreate.userErrors.length||!created.productCreate.product)throw new Error(created.productCreate.userErrors.map(e=>e.message).join("; ")||"Shopify did not create the product");const shopifyProduct=created.productCreate.product,variantId=shopifyProduct.variants.nodes[0]?.id;if(!variantId)throw new Error("Shopify product has no default variant");try{return await updateShopifyProduct(product,{id:variantId,sku:product.code,product:{id:shopifyProduct.id,title:product.name},inventoryItem:{id:"",tracked:true}},false);}catch(error){await shopifyGraphql(`mutation Cleanup($input:ProductDeleteInput!){productDelete(input:$input){deletedProductId}}`,{input:{id:shopifyProduct.id}}).catch(()=>undefined);throw error;}}

export async function updateShopifyProduct(product:KiotVietProduct,variant:ShopifyVariant,addMissingMedia=true):Promise<ManagedVariant>{const media=addMissingMedia&&!await productHasMedia(variant.product.id)?productMedia(product):[];const updated=await shopifyGraphql<{productUpdate:{product?:{id:string};userErrors:Array<{message:string}>}}>(`mutation UpdateProduct($product:ProductUpdateInput!,$media:[CreateMediaInput!]){productUpdate(product:$product,media:$media){product{id} userErrors{message}}}`,{product:{id:variant.product.id,...productInput(product)},media});if(updated.productUpdate.userErrors.length)throw new Error(updated.productUpdate.userErrors.map(e=>e.message).join("; "));const result=await shopifyGraphql<{productVariantsBulkUpdate:{productVariants:ManagedVariant[];userErrors:Array<{message:string}>}}>(`mutation UpdateVariant($productId:ID!,$variants:[ProductVariantsBulkInput!]!){productVariantsBulkUpdate(productId:$productId,variants:$variants){productVariants{id sku barcode price product{id title} inventoryItem{id tracked}} userErrors{message}}}`,{productId:variant.product.id,variants:[{id:variant.id,price:String(product.basePrice??0),barcode:product.barCode||null,inventoryItem:{sku:product.code,tracked:true}}]});if(result.productVariantsBulkUpdate.userErrors.length||!result.productVariantsBulkUpdate.productVariants[0])throw new Error(result.productVariantsBulkUpdate.userErrors.map(e=>e.message).join("; ")||"Shopify did not update the variant");return result.productVariantsBulkUpdate.productVariants[0];}
