import { getKiotVietProduct } from "@/lib/kiotviet/products";
import { createShopifyProduct, findShopifyVariantsBySku, updateShopifyProduct } from "@/lib/shopify/products";
import { mappingsRepository } from "@/repositories/mappings";
import { normalizeSku } from "./mappings";
import { syncHash } from "./hashes";
import { syncInventoryNotification } from "./inventory-sync";
import { query } from "@/lib/db/client";
import { log } from "@/lib/logger";

export async function syncKiotVietProductToShopify(productId:number,jobId?:string){const product=await getKiotVietProduct(productId),sku=normalizeSku(product.code);if(!sku)throw new Error(`KiotViet product ${productId} has no SKU`);const state={name:product.name,description:product.description??"",categoryName:product.categoryName??"",basePrice:product.basePrice??0,barCode:product.barCode??"",isActive:product.isActive!==false,allowsSale:product.allowsSale!==false,images:product.images??[]};const hash=syncHash(state);const mappings=await mappingsRepository.findBySku(sku);let variant=mappings.length===1&&mappings[0].shopify_variant_id?{id:mappings[0].shopify_variant_id,sku:product.code,product:{id:mappings[0].shopify_product_id!,title:product.name},inventoryItem:{id:mappings[0].shopify_inventory_item_id!,tracked:true}}:undefined;if(mappings.length===1&&mappings[0].last_sync_hash===hash)return{sku,updated:false,reason:"unchanged"};if(!variant){const matches=await findShopifyVariantsBySku(product.code);if(matches.length>1)throw new Error(`Multiple Shopify variants found for SKU ${sku}`);variant=matches[0];}const saved=variant?await updateShopifyProduct(product,variant):await createShopifyProduct(product);await mappingsRepository.upsert({sku:product.code,normalized_sku:sku,shopify_product_id:saved.product.id,shopify_variant_id:saved.id,shopify_inventory_item_id:saved.inventoryItem.id,kiotviet_product_id:String(product.id),kiotviet_code:product.code,sync_direction:"kiotviet_to_shopify"});await query("UPDATE product_mappings SET last_sync_hash=$2,last_source='kiotviet',last_kiotviet_sync_at=now(),sync_status='synced',updated_at=now() WHERE normalized_sku=$1",[sku,hash]);for(const inventory of product.inventories??[])await syncInventoryNotification({ProductId:product.id,ProductCode:product.code,ProductName:product.name,BranchId:inventory.branchId,BranchName:inventory.branchName,Cost:0,OnHand:inventory.onHand,Reserved:inventory.reserved??inventory.actualReserved??0},jobId);await log("info","KiotViet product synchronized to Shopify",{action:"update_shopify_product",provider:"shopify",entityType:"product",entityId:sku,jobId});return{sku,updated:true};}
