"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type ManualAction={action:string;title:string;description:string;label:string;input?:{name:string;label:string;placeholder:string};danger?:boolean};
const actions:ManualAction[]=[
  {action:"mappings",title:"Quét ánh xạ sản phẩm",description:"Ghép SKU giữa Shopify và KiotViet, đồng thời ghi nhận SKU thiếu hoặc trùng.",label:"Chạy quét mapping"},
  {action:"products",title:"Đồng bộ toàn bộ sản phẩm",description:"Đọc lại danh sách sản phẩm và cập nhật mapping hiện có.",label:"Đồng bộ sản phẩm"},
  {action:"inventory",title:"Đối soát tồn kho",description:"Lấy tồn kho KiotViet và cập nhật số lượng Shopify theo từng chi nhánh đã cấu hình.",label:"Đồng bộ tồn kho"},
  {action:"returns",title:"Quét phiếu trả hàng",description:"Tìm phiếu trả mới từ KiotViet và đưa vào hàng đợi hoàn tiền Shopify.",label:"Quét trả hàng",danger:true},
  {action:"product",title:"Đồng bộ một sản phẩm",description:"Cập nhật ngay sản phẩm và variant Shopify từ một sản phẩm KiotViet.",label:"Đồng bộ sản phẩm",input:{name:"productId",label:"KiotViet product ID",placeholder:"Nhập product ID"}},
  {action:"return",title:"Đồng bộ một phiếu trả",description:"Tạo refund và giao dịch hoàn tiền Shopify cho đúng phiếu trả KiotViet.",label:"Hoàn tiền",input:{name:"returnId",label:"KiotViet return ID",placeholder:"Nhập return ID"},danger:true},
  {action:"tracking",title:"Đồng bộ tracking",description:"Lấy mã vận đơn từ hóa đơn KiotViet và tạo hoặc cập nhật fulfillment Shopify.",label:"Cập nhật tracking",input:{name:"invoiceId",label:"KiotViet invoice ID",placeholder:"Nhập invoice ID"}},
];
export function ManualActions(){const router=useRouter(),[values,setValues]=useState<Record<string,string>>({}),[states,setStates]=useState<Record<string,string>>({});async function run(item:ManualAction){if(item.input&&!values[item.action]?.trim()){setStates(s=>({...s,[item.action]:`Vui lòng nhập ${item.input?.label}`}));return;}if(item.danger&&!window.confirm(`${item.title}: bạn chắc chắn muốn tiếp tục?`))return;setStates(s=>({...s,[item.action]:"Đang đưa vào hàng đợi…"}));try{const response=await fetch(`/api/admin/sync/${item.action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item.input?{[item.input.name]:values[item.action]}:{})}),body=await response.json() as {jobId?:string;error?:string};setStates(s=>({...s,[item.action]:response.ok?`Đã tạo job ${body.jobId??""}`:body.error??"Không thể tạo job"}));if(response.ok)router.refresh();}catch{setStates(s=>({...s,[item.action]:"Không thể kết nối máy chủ"}));}}return <section className="manual-grid">{actions.map(item=><article className={`manual-card${item.danger?" manual-card-danger":""}`} key={item.action}><div><span className="manual-tag">{item.danger?"Cần xác nhận":"Thao tác an toàn"}</span><h2>{item.title}</h2><p>{item.description}</p></div>{item.input&&<label>{item.input.label}<input inputMode="numeric" value={values[item.action]??""} placeholder={item.input.placeholder} onChange={event=>setValues(value=>({...value,[item.action]:event.target.value}))}/></label>}<div className="manual-footer"><button onClick={()=>void run(item)}>{item.label}</button><small>{states[item.action]}</small></div></article>)}</section>}
