"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type ManualAction={action:string;title:string;description:string;label:string;input?:{name:string;label:string;placeholder:string};danger?:boolean};
const actions:ManualAction[]=[
 {action:"mappings",title:"Scan product mappings",description:"Match Shopify and KiotViet SKUs, then report missing or duplicate values.",label:"Scan mappings"},
 {action:"products",title:"Synchronize all products",description:"Reload the product catalog and update existing mappings.",label:"Sync products"},
 {action:"inventory",title:"Reconcile inventory",description:"Read KiotViet inventory and update Shopify quantities for configured branches.",label:"Sync inventory"},
 {action:"returns",title:"Scan returns",description:"Find new KiotViet returns and queue Shopify refunds.",label:"Scan returns",danger:true},
 {action:"product",title:"Synchronize one product",description:"Update a Shopify product and its variants from one KiotViet product.",label:"Sync product",input:{name:"productId",label:"KiotViet product ID",placeholder:"Enter product ID"}},
 {action:"return",title:"Synchronize one return",description:"Create a Shopify refund and refund transaction for a KiotViet return.",label:"Process refund",input:{name:"returnId",label:"KiotViet return ID",placeholder:"Enter return ID"},danger:true},
 {action:"tracking",title:"Synchronize tracking",description:"Read tracking from a KiotViet invoice and create or update the Shopify fulfillment.",label:"Update tracking",input:{name:"invoiceId",label:"KiotViet invoice ID",placeholder:"Enter invoice ID"}},
];
export function ManualActions(){const router=useRouter(),[values,setValues]=useState<Record<string,string>>({}),[states,setStates]=useState<Record<string,string>>({}),[running,setRunning]=useState<string>("");async function run(item:ManualAction){if(item.input&&!values[item.action]?.trim()){setStates(s=>({...s,[item.action]:`Enter ${item.input?.label}`}));return}if(item.danger&&!window.confirm(`${item.title}: are you sure you want to continue?`))return;setRunning(item.action);setStates(s=>({...s,[item.action]:"Adding to queue..."}));try{const response=await fetch(`/api/admin/sync/${item.action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item.input?{[item.input.name]:values[item.action]}:{})}),body=await response.json() as {jobId?:string;error?:string};setStates(s=>({...s,[item.action]:response.ok?`Queued job ${body.jobId??""}`:body.error??"Unable to queue job"}));if(response.ok)router.refresh()}catch{setStates(s=>({...s,[item.action]:"Unable to connect to the server"}))}finally{setRunning("")}}return <section className="manual-grid">{actions.map(item=><article className={`manual-card${item.danger?" manual-card-danger":""}`} key={item.action}><div><span className="manual-tag">{item.danger?"Confirmation required":"Standard action"}</span><h2>{item.title}</h2><p>{item.description}</p></div>{item.input&&<label>{item.input.label}<input inputMode="numeric" value={values[item.action]??""} placeholder={item.input.placeholder} onChange={event=>setValues(value=>({...value,[item.action]:event.target.value}))}/></label>}<div className="manual-footer"><button className={`button ${item.danger?"button-danger":"button-primary"}`} type="button" disabled={Boolean(running)} onClick={()=>void run(item)}>{running===item.action?"Queueing...":item.label}</button><small>{states[item.action]}</small></div></article>)}</section>}
