import { getEnv } from "@/lib/env";
import { AuthenticationError, RetryableError } from "@/lib/errors";
import { getRedis, isRedisEnabled } from "@/lib/redis/client";
const TOKEN_URL="https://id.kiotviet.vn/connect/token",CACHE_KEY="kiotviet:access-token";
let localToken: { value: string; expiresAt: number } | undefined;
interface TokenResponse{access_token:string;expires_in:number}
function valid(v:unknown):v is TokenResponse{const x=v as Partial<TokenResponse>;return !!x&&typeof x.access_token==="string"&&typeof x.expires_in==="number";}
export async function clearKiotVietAccessToken(){if(isRedisEnabled())await getRedis().del(CACHE_KEY);else localToken=undefined;}
export async function getKiotVietAccessToken(force=false){const env=getEnv();if(!env.KIOTVIET_CLIENT_ID||!env.KIOTVIET_CLIENT_SECRET||!env.KIOTVIET_RETAILER)throw new AuthenticationError("KiotViet credentials are not configured");if(!force){if(isRedisEnabled()){const cached=await getRedis().get(CACHE_KEY);if(cached)return cached;}else if(localToken&&localToken.expiresAt>Date.now())return localToken.value;}let response:Response;try{response=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({scopes:"PublicApi.Access",grant_type:"client_credentials",client_id:env.KIOTVIET_CLIENT_ID,client_secret:env.KIOTVIET_CLIENT_SECRET}),signal:AbortSignal.timeout(15000),cache:"no-store"});}catch{throw new RetryableError("Could not connect to KiotViet authentication service");}if(!response.ok)throw new AuthenticationError(`KiotViet authentication failed (${response.status})`);let payload:unknown;try{payload=await response.json();}catch{throw new AuthenticationError("KiotViet authentication returned invalid JSON");}if(!valid(payload))throw new AuthenticationError("KiotViet authentication response is invalid");const ttl=Math.max(1,payload.expires_in-60);if(isRedisEnabled())await getRedis().set(CACHE_KEY,payload.access_token,"EX",ttl);else localToken={value:payload.access_token,expiresAt:Date.now()+ttl*1_000};return payload.access_token;}
